apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: uday # required field for kubernetes.io/basic-auth
  password: 123@dbpass # required field for kubernetes.io/basic-auth
